name: E2E (iOS)
run-name: Running E2E tests on iOS 🚀

on:
  pull_request:
    branches: [master]
  push:
    branches: [dev-41-actions]

jobs:
  build:
    name: E2E (iOS)
    runs-on: macOS-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..
      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Run Detox Build
        run: yarn e2e:build ios.sim.release
      - name: Run Detox Test(s)
        run: bash ${{ github.workspace }}/scripts/run-e2e-ios-release.sh
